### ISSUE TITLE
url annotated_image

### ISSUE THREAD

**Issue by hvanstappen** [datable-be/AI4C_ContentAnalysis#1]
base url of the annotated_image is ''http://localhost:8000/' (hardcoded?), should be same base url as service (e.g. http://lego.image.ece.ntua.gr:8000/) 

see response message:
```
Successfully processed image: http://datable.be/files/image_analysis_test/samples4/man.jpg
{'detection_id': '83771a9c04abbf58a37b6d0340d0ae029f37b11d', 'request_id': 'http://datable.be/files/image_analysis_test/samples4/man.jpg', 'data': [{'confidence': 0.8131583333015442, 'size': 5280, 'box (px)': [136, 39, 176, 171], 'box (%)': [45.48, 13.04, 88.0, 85.5], 'coco_label': 'person', 'wikidata': {'wikidata_concepturi': 'http://www.wikidata.org/entity/Q215627', 'wikidata_label': 'person', 'wikidata_description': 'being that has certain capacities or attributes constituting personhood (avoid use with P31; use Q5 for humans)', 'wikidata_concept': 'Q215627'}, 'annotated_image': 'http://localhost:8000/image?img=83771a9c04abbf58a37b6d0340d0ae029f37b11d_1.jpg'}]}
```

**Comment by TomDeneire** [comment]
Host name and port are actually configurable in the `settings.json` file (https://github.com/datable-be/AI4C_ContentAnalysis/blob/main/development/app/settings.json). I've added a section about these settings to the documentation https://github.com/datable-be/AI4C_ContentAnalysis/commit/0dae6dbdf507a21d9b79e4a2b9088b85beb0837b
