### ISSUE TITLE
error in gray scale or B/W detection

### ISSUE THREAD

**Issue by hvanstappen** [datable-be/AI4C_ContentAnalysis#3]
(tested with http://localhost:8000/ui/color)
With the Blip-vqa-base method, the Warning messages for black&white or grayscale images seem wrong:
* color image: warning "image is in b/w or grayscale"
* color image with very low saturation: warning (OK)
* grayscale image: no warning
* bitonal image: warning (OK)

Although it seems the internal method uses the same function, in this case the gray scale or B/W detection seems to be correct

**Comment by TomDeneire** [comment]
The difference is in the fact that with internal labeling the image is resized in the function `determine_image`, whereas with blip this does not occur. I don't see why that should matter to the `is_quasi_monochrome_with_rgb` function (specifically the values for `r.getextrema() == g.getextrema() == b.getextrema()` are different), but will investigate further.

**Comment by TomDeneire** [comment]
https://github.com/datable-be/AI4C_ContentAnalysis/commit/6cd6afdb3cffba75fc2e898e92deff452b84ba73
